"use client";

import { useMemo, useRef } from 'react';
import type { Notification, Client, Vehicle, Partner, FinancialRecord, VehicleWithMileage } from '@/types';
import { differenceInDays } from 'date-fns';
import { infallibleNormalizeDate } from '@/lib/date-utils';
import { useAuth } from '@/contexts/auth-provider';
import { useQuery } from '@tanstack/react-query';
import type { ClientMetric } from './use-client-analytics';
import { formatCurrency } from '@/lib/utils';
import { supabase } from '@/lib/supabase';

export type AnalyzedNotification = Notification & {
  priority: 'Crítica' | 'Alta' | 'Media' | 'Baja';
  category: 'Mantenimiento' | 'Financiera' | 'Legal' | 'Operacional';
  urgencyScore: number;
  entityType: 'Vehículo' | 'Cliente' | 'Socio' | 'Sistema';
  relatedEntityType: 'Vehicle' | 'Client' | 'Partner' | 'System';
  actionRequired: boolean;
  estimatedImpact: 'Alto' | 'Medio' | 'Bajo';
  isAutoGenerated: boolean;
  icon?: React.ReactNode;
  timestamp?: string;
};

const MAINTENANCE_URGENCY_THRESHOLD_KM = 0;
const MAINTENANCE_HIGH_THRESHOLD_KM = 1500;
const EXPIRY_URGENCY_THRESHOLD_DAYS = 0;
const EXPIRY_HIGH_THRESHOLD_DAYS = 30;
const HIGH_BALANCE_THRESHOLD = 5000;

const useMemoDeep = <T,>(factory: () => T, deps: any[]): T => {
  const ref = useRef<{ deps: any[], value: T } | undefined>(undefined);
  const depsString = JSON.stringify(deps);
  if (!ref.current || JSON.stringify(ref.current.deps) !== depsString) {
    ref.current = { deps, value: factory() };
  }
  return ref.current.value;
};

export const useNotificationsAnalytics = (
  notifications: Notification[],
  clients: Client[],
  vehicles: VehicleWithMileage[],
  partners: Partner[],
  financialRecords: FinancialRecord[],
  clientBalances: { id: string; balance: number; }[]
) => {
  const { currentUser } = useAuth();
  const userId = currentUser?.id;

  // Las alertas automáticas no existen como filas en notifications.
  // Su estado de lectura se persiste por usuario mediante una clave estable.
  const { data: readStateRows = [] } = useQuery<{ notification_key: string; read_at: string }[]>({
    queryKey: ['notification-read-states', userId],
    queryFn: async () => {
      if (!userId) return [];
      const { data, error } = await (supabase as any)
        .from('notification_read_states')
        .select('notification_key, read_at')
        .eq('user_id', userId);
      if (error) throw error;
      return data || [];
    },
    enabled: !!userId,
    staleTime: 0,
    refetchOnWindowFocus: true,
  });

  const readStateKeys = useMemo(() => new Set(readStateRows.map(row => row.notification_key)), [readStateRows]);

  const analyzedNotifications = useMemoDeep(() => {
    const isSuperAdmin = currentUser?.role === 'superAdmin';
    const companyId = currentUser?.companyId;
    const companyVehicles = isSuperAdmin ? vehicles : vehicles.filter(v => v.companyId === companyId);
    const companyClients = isSuperAdmin ? clients : clients.filter(c => c.companyId === companyId);
    const companyBalances = clientBalances.filter(cb => companyClients.some(cc => cc.id === cb.id));
    const clientMap = new Map(companyClients.map(c => [c.id, c]));
    const now = new Date();
    const allGeneratedNotifications: AnalyzedNotification[] = [];

    companyVehicles.forEach(vehicle => {
      if (vehicle.status === 'sold' || vehicle.isDeleted) return;
      const kmToMaint = vehicle.kmToNextMaintenance;
      if (kmToMaint === undefined) return;
      let priority: AnalyzedNotification['priority'] | null = null;
      let urgencyScore = 0;
      let message = '';
      const assignedClient = vehicle.clientId ? clientMap.get(vehicle.clientId) : null;
      const clientNameStr = assignedClient ? ` (Asignado a: ${assignedClient.firstname} ${assignedClient.lastname})` : '';
      if (kmToMaint <= MAINTENANCE_URGENCY_THRESHOLD_KM) {
        priority = 'Crítica'; urgencyScore = 95 - Math.min(Math.floor(kmToMaint / 1000), 5);
        message = `Mtto. Vencido: ${vehicle.plate} excedido por ${Math.abs(kmToMaint).toLocaleString()} km.${clientNameStr}`;
      } else if (kmToMaint <= MAINTENANCE_HIGH_THRESHOLD_KM) {
        priority = 'Alta'; urgencyScore = 80 - Math.floor(kmToMaint / 200);
        message = `Próximo Mtto: ${vehicle.plate} en ${kmToMaint.toLocaleString()} km.${clientNameStr}`;
      }
      if (priority) {
        const id = `maint_alert_${vehicle.id}`;
        allGeneratedNotifications.push({ id, uid: id, type: 'maintenance_mileage', message, date: now.toISOString(), relatedId: vehicle.id, isRead: readStateKeys.has(id), priority, category: 'Mantenimiento', urgencyScore, entityType: 'Vehículo', relatedEntityType: 'Vehicle', actionRequired: true, estimatedImpact: priority === 'Crítica' ? 'Alto' : 'Medio', isAutoGenerated: true, companyId: vehicle.companyId });
      }
    });

    companyVehicles.forEach(vehicle => {
      if (vehicle.status === 'sold' || vehicle.isDeleted) return;
      const insExpiryDate = infallibleNormalizeDate(vehicle.insuranceExpiryDate);
      if (!insExpiryDate) return;
      const daysLeft = differenceInDays(insExpiryDate, now);
      let priority: AnalyzedNotification['priority'] | null = null;
      let urgencyScore = 0;
      let message = '';
      const assignedClient = vehicle.clientId ? clientMap.get(vehicle.clientId) : null;
      const clientNameStr = assignedClient ? ` (Asignado a: ${assignedClient.firstname} ${assignedClient.lastname})` : '';
      if (daysLeft <= EXPIRY_URGENCY_THRESHOLD_DAYS) { priority = 'Crítica'; urgencyScore = 90; message = `Seguro Vencido: La póliza del vehículo ${vehicle.plate}${clientNameStr} ha vencido.`; }
      else if (daysLeft <= EXPIRY_HIGH_THRESHOLD_DAYS) { priority = 'Alta'; urgencyScore = 75 - daysLeft; message = `Seguro por Vencer: La póliza de ${vehicle.plate}${clientNameStr} vence en ${daysLeft} días.`; }
      if (priority) {
        const id = `ins_alert_${vehicle.id}`;
        allGeneratedNotifications.push({ id, uid: id, type: 'insurance_expiry', message, date: now.toISOString(), relatedId: vehicle.id, isRead: readStateKeys.has(id), priority, category: 'Legal', urgencyScore, entityType: 'Vehículo', relatedEntityType: 'Vehicle', actionRequired: true, estimatedImpact: priority === 'Crítica' ? 'Alto' : 'Medio', isAutoGenerated: true, companyId: vehicle.companyId });
      }
    });

    companyClients.forEach(client => {
      if (client.status === 'inactive' || client.isDeleted) return;
      const licExpiryDate = infallibleNormalizeDate(client.licenseExpiry);
      if (!licExpiryDate) return;
      const daysLeft = differenceInDays(licExpiryDate, now);
      let priority: AnalyzedNotification['priority'] | null = null;
      let urgencyScore = 0;
      let message = '';
      const clientNameStr = `${client.firstname} ${client.lastname}` || 'Cliente desconocido';
      if (daysLeft <= EXPIRY_URGENCY_THRESHOLD_DAYS) { priority = 'Crítica'; urgencyScore = 88; message = `Licencia Vencida: La licencia de ${clientNameStr} ha vencido.`; }
      else if (daysLeft <= EXPIRY_HIGH_THRESHOLD_DAYS) { priority = 'Alta'; urgencyScore = 73 - daysLeft; message = `Licencia por Vencer: La licencia de ${clientNameStr} vence en ${daysLeft} días.`; }
      if (priority) {
        const id = `lic_alert_${client.id}`;
        allGeneratedNotifications.push({ id, uid: id, type: 'license_expiry', message, date: now.toISOString(), relatedId: client.id, isRead: readStateKeys.has(id), priority, category: 'Legal', urgencyScore, entityType: 'Cliente', relatedEntityType: 'Client', actionRequired: true, estimatedImpact: 'Alto', isAutoGenerated: true, companyId: client.companyId });
      }
    });

    companyBalances.forEach(client => {
      const clientData = clientMap.get(client.id);
      if (clientData && clientData.status === 'active' && !clientData.isDeleted && client.balance > HIGH_BALANCE_THRESHOLD) {
        const id = `balance_alert_${client.id}`;
        allGeneratedNotifications.push({ id, uid: id, type: 'driver_payment_pending', message: `Cliente ${clientData.firstname} ${clientData.lastname} tiene un saldo pendiente elevado de ${formatCurrency(client.balance)}`, date: now.toISOString(), relatedId: client.id, isRead: readStateKeys.has(id), priority: 'Alta', category: 'Financiera', urgencyScore: 85, entityType: 'Cliente', relatedEntityType: 'Client', actionRequired: true, estimatedImpact: 'Medio', isAutoGenerated: true, companyId: clientData.companyId });
      }
    });

    const processedExisting = (notifications || []).map(n => ({ ...n, priority: 'Baja', category: 'Operacional', urgencyScore: 10, entityType: 'Sistema', relatedEntityType: 'System', actionRequired: false, estimatedImpact: 'Bajo', isAutoGenerated: false } as AnalyzedNotification));
    const combined = [...allGeneratedNotifications, ...processedExisting];
    return Array.from(new Map(combined.map(n => [n.id, n])).values()).sort((a, b) => b.urgencyScore - a.urgencyScore);
  }, [currentUser, notifications, clients, vehicles, partners, financialRecords, clientBalances, readStateKeys]);

  return { analyzedNotifications };
};
