"use client";

import { useCallback, useMemo, useState } from "react";
import Link from "next/link";
import { Bell, Check, CheckCheck } from "lucide-react";
import { formatDistanceToNow } from "date-fns";
import { es } from "date-fns/locale";
import { useQueryClient } from "@tanstack/react-query";
import { useAuth } from "@/contexts/auth-provider";
import { useData } from "@/hooks/use-data";
import { useNotificationsAnalytics } from "@/hooks/use-notifications-analytics";
import { supabase } from "@/lib/supabase";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";

const TYPE_LABELS: Record<string, string> = {
  credit_payment_received: "Pago de crédito",
  vehicle_maintenance_due: "Mantenimiento",
  maintenance_mileage: "Mantenimiento",
  insurance_expiring: "Seguro",
  insurance_expiry: "Seguro",
  license_expiring: "Licencia",
  license_expiry: "Licencia",
  balance_updated: "Balance",
  driver_payment_pending: "Saldo pendiente",
  announcement: "Aviso",
};

export function UnreadNotificationsCard() {
  const { currentUser } = useAuth();
  const queryClient = useQueryClient();
  const {
    notifications: rawNotifications = [],
    clients = [],
    vehicles = [],
    partners = [],
    financialRecords = [],
    clientBalances = [],
    markNotificationAsRead,
  } = useData() as any;

  const { analyzedNotifications } = useNotificationsAnalytics(
    rawNotifications,
    clients,
    vehicles,
    partners,
    financialRecords,
    clientBalances
  );

  const [readOverrides, setReadOverrides] = useState<Set<string>>(() => new Set());
  const [busy, setBusy] = useState(false);

  const unread = useMemo(() => {
    return analyzedNotifications
      .map((n) => (readOverrides.has(n.id) ? { ...n, isRead: true } : n))
      .filter((n) => !n.isRead)
      .sort((a, b) => {
        // Prioridad por urgencia, luego fecha
        const urg = (b.urgencyScore || 0) - (a.urgencyScore || 0);
        if (urg !== 0) return urg;
        const da = new Date(a.date || 0).getTime();
        const db = new Date(b.date || 0).getTime();
        return db - da;
      })
      .slice(0, 10);
  }, [analyzedNotifications, readOverrides]);

  const markAsRead = useCallback(
    async (id: string) => {
      const notification = analyzedNotifications.find((n) => n.id === id);
      if (!notification || notification.isRead || readOverrides.has(id)) return;

      setReadOverrides((prev) => {
        const next = new Set(prev);
        next.add(id);
        return next;
      });

      try {
        const readAt = new Date().toISOString();

        if (notification.isAutoGenerated) {
          const { data: userData } = await supabase.auth.getUser();
          const userId = userData.user?.id;
          if (!userId) throw new Error("Usuario no identificado");

          const { error } = await supabase.from("notification_read_states").upsert(
            {
              user_id: userId,
              notification_key: id,
              read_at: readAt,
            },
            { onConflict: "user_id,notification_key" }
          );
          if (error) throw error;
        } else if (typeof markNotificationAsRead === "function") {
          await markNotificationAsRead(id);
        } else {
          const { error } = await supabase
            .from("notifications")
            .update({ is_read: true, read_at: readAt })
            .eq("id", id);
          if (error) throw error;
        }

        await queryClient.invalidateQueries({ queryKey: ["notifications"] });
        await queryClient.invalidateQueries({ queryKey: ["notification-read-states"] });
      } catch (err) {
        setReadOverrides((prev) => {
          const next = new Set(prev);
          next.delete(id);
          return next;
        });
        console.error(err);
        toast.error("No se pudo marcar como leída");
      }
    },
    [analyzedNotifications, readOverrides, markNotificationAsRead, queryClient]
  );

  const markAll = useCallback(async () => {
    if (unread.length === 0) return;
    setBusy(true);
    try {
      for (const n of unread) {
        await markAsRead(n.id);
      }
      toast.success("Notificaciones marcadas como leídas");
    } catch {
      toast.error("No se pudieron actualizar todas las notificaciones");
    } finally {
      setBusy(false);
    }
  }, [unread, markAsRead]);

  return (
    <div className="flex h-full min-h-[240px] flex-col overflow-hidden rounded-[16px] border border-white/[0.08] bg-[#0e1117] shadow-[0_12px_40px_rgba(0,0,0,.2)]">
      <div className="flex items-center justify-between gap-2 border-b border-white/[0.06] px-4 py-3">
        <div className="flex items-center gap-2 min-w-0">
          <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg border border-[#d7ff3f]/20 bg-[#d7ff3f]/[0.08] text-[#d7ff3f]">
            <Bell className="h-4 w-4" strokeWidth={1.75} />
          </div>
          <div className="min-w-0">
            <p className="text-sm font-semibold text-white">Notificaciones sin leer</p>
            <p className="text-[11px] text-white/40">
              {unread.length === 0
                ? "Todo al día"
                : `${unread.length} pendiente${unread.length === 1 ? "" : "s"}`}
            </p>
          </div>
        </div>
        <div className="flex shrink-0 items-center gap-1">
          {unread.length > 0 && (
            <Button
              type="button"
              variant="ghost"
              size="sm"
              disabled={busy}
              onClick={markAll}
              className="h-8 px-2 text-[11px] text-white/50 hover:bg-white/[0.06] hover:text-white"
            >
              <CheckCheck className="mr-1 h-3.5 w-3.5" strokeWidth={1.75} />
              Leer todas
            </Button>
          )}
          <Button
            type="button"
            variant="ghost"
            size="sm"
            asChild
            className="h-8 px-2 text-[11px] text-white/50 hover:bg-white/[0.06] hover:text-white"
          >
            <Link href="/dashboard/notifications">Ver todas</Link>
          </Button>
        </div>
      </div>

      <div className="flex-1 space-y-1 overflow-y-auto p-2">
        {!currentUser ? (
          <p className="px-3 py-8 text-center text-sm text-white/35">Inicia sesión para ver avisos.</p>
        ) : unread.length === 0 ? (
          <p className="px-3 py-8 text-center text-sm text-white/35">
            No tienes notificaciones sin leer.
          </p>
        ) : (
          unread.map((n) => (
            <button
              key={n.id}
              type="button"
              onClick={() => markAsRead(n.id)}
              className={cn(
                "flex w-full flex-col gap-1 rounded-xl border border-[#d7ff3f]/10 bg-[#d7ff3f]/[0.03] px-3 py-2.5 text-left transition-colors",
                "hover:border-[#d7ff3f]/25 hover:bg-[#d7ff3f]/[0.06]"
              )}
            >
              <div className="flex items-start justify-between gap-2">
                <p className="text-sm font-semibold text-white/90">
                  {TYPE_LABELS[n.type] || n.category || n.type || "Aviso"}
                  {n.priority ? (
                    <span className="ml-2 text-[10px] font-medium text-white/35">{n.priority}</span>
                  ) : null}
                </p>
                <Check className="mt-0.5 h-3.5 w-3.5 shrink-0 text-white/25" strokeWidth={1.75} />
              </div>
              <p className="line-clamp-2 text-xs text-white/55">{n.message}</p>
              <p className="text-[10px] text-white/30">
                {n.date
                  ? formatDistanceToNow(new Date(n.date), { addSuffix: true, locale: es })
                  : ""}
              </p>
            </button>
          ))
        )}
      </div>
    </div>
  );
}
